version: "3.9"
services:
  localstack:
    container_name: "${APP_NAME}-localstack"
    image: localstack/localstack-pro:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4560:4510-4560"  # external services port range
      - "8001:8080"            # only required for Pro
      - "443:443"              # LocalStack HTTPS Gateway (required for Pro)
      - "4571:4571"            # elasticsearch service
    environment:
      - DEBUG=1 # turn debug output on
      - ENFORCE_IAM=${ENFORCE_IAM-0} # Enable IAM policy evaluation and enforcement
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=90
      - PERSIST_ALL=${PERSIST_ALL-false}
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN-}
      - ECS_DOCKER_FLAGS=-e NODE_OPTIONS=--inspect-brk=0.0.0.0:9229 -p 9229:9229  # Optional flag required for remote debugging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket into the container
